### ISSUE TITLE
Windows-compatible ishell not yet uploaded to PyPI

### ISSUE THREAD

**Issue by unicornsasfuel** [italorossi/ishell#29]
The version of `ishell` on PyPI fails to install on Windows since the latest pull request which fixes that issue has not been put up on PyPI.

(Yes, I know you only accepted that PR yesterday but I'm very excited for FeatherDuster to finally be installable via pip :)

**Comment by italorossi** [comment]
Bumped version in 36c2c7002a471952e402d1f665c5ae7622e3cbf4

Pushed to PyPI.

**Comment by olivren** [comment]
The latest version on PyPI (0.1.7) still cannot be installed on Windows. The setup.py fails with `FileNotFoundError: [Errno 2] No such file or directory: 'win_requirements.txt'`. The file `win_requirements.txt` is indeed not packaged in the tarball.

**Comment by italorossi** [comment]
Just added in the MANIFEST file and published as 0.1.8. Could you check if it works now?

**Comment by olivren** [comment]
Yes it works great! Thanks a lot.
